Humble desired pose check
saha-robotics/slam_toolbox_fork pull request #15
Opened 2024-09-24 05:35 UTC by Renbago

## Basic Info

this pr include desiredPoseChecker service in slam_toolbox_localization, and few more karto_debug

---

## What's added ?

This service basicly using the same logic with 2d pose. But changing the angle offset,dimension's, min_distance, and few more settings. We are triggering karto for desired solution with desired settings. Service file returns best_response reloceted_x reloceted_y for best Solution. We are able to access those data with ```GetBestResponse``` function

## service type:
```'slam_toolbox/desired_pose_check'```
## referance service call
```ros2 service call /SR5S1/slam_toolbox/desired_pose_check slam_toolbox/srv/DesiredPoseChecker "{pose_x: 0.7, pose_y: 0.26, do_relocalization: true, search_distance: 12.0}"```

## Description of documentation updates required from your changes
those parameters need to add slam_toolbox.yaml
```
position_search_distance: 16.0   
position_search_resolution: 0.05
position_search_smear_deviation: 0.03
position_search_fine_angle_offset: 0.00349
position_search_coarse_angle_offset: 3.14
position_search_coarse_angle_resolution: 0.0349
position_search_do_relocalization: true
```
---

## Future 
?

2024-09-24 05:36 UTC, Renbago commented
Currently do not accept this version. Its still test version, I might be need changes few more.

2024-09-27 07:11 UTC, Zarqu0n commented
Is this okay to merge?

2024-09-27 07:12 UTC, Renbago commented
> Is this okay to merge? @Renbago 

Not yet,

2024-09-27 07:20 UTC, Zarqu0n requested changes

2024-09-27 07:20 UTC, Zarqu0n commented on lib/karto_sdk/src/Mapper.cpp
> +  // mx ve my poses  benim grid size ımdaki resamplelanmış pose ları tekabul ediyor
is it important?

2024-09-27 07:20 UTC, Zarqu0n commented on lib/karto_sdk/src/Mapper.cpp
> +  end = std::chrono::steady_clock::now();
is this publish message when robot normal working?

2024-09-27 07:20 UTC, Zarqu0n commented on lib/karto_sdk/src/Mapper.cpp
> +    std::cout << "-----------------the next scan match is from trycloseloop------------" << std::endl;
is this publish message when robot normal working?

2024-09-27 07:20 UTC, Zarqu0n commented on lib/karto_sdk/src/Mapper.cpp
> +  std::cout << "m_pFineSearchAngleOffset: " << *m_pFineSearchAngleOffset << std::endl;
is this publish message when robot normal working?

2024-09-27 07:20 UTC, Zarqu0n commented on lib/karto_sdk/src/Mapper.cpp
Please make sure that the robot does not log when operating normally. You can test this to disable navigation.

2024-09-27 07:20 UTC, Zarqu0n commented on src/slam_toolbox_common.cpp
I thing we need to test any garbage variable. Maybe some variable were forgotten.

2024-09-27 08:41 UTC, Renbago commented on src/slam_toolbox_common.cpp
yeah i know i will clean those, beacuse of that i wrote do not merge.

2024-10-01 05:51 UTC, Renbago commented
@Zarqu0n review

2024-10-01 06:07 UTC, Zarqu0n reviewed
Did you test in robot? Has publish any useless log message.

2024-10-01 07:17 UTC, Renbago commented
> Did you test in robot? Has publish any useless log message.

yes but i have find bug do not merge.

2024-10-01 10:13 UTC, Renbago commented
I'ts okay now.

2024-10-01 10:20 UTC, Renbago commented
### If service called:
the terminal first output:
```
[map_and_localization_slam_toolbox_node-1] [INFO] [1727777866.250428241] [SR5S1.slam_toolbox]: LocalizationSlamToolbox: Searching for best response with relocalize 
```

the reference service response with call:
```
ros2 service call /SR5S1/slam_toolbox/desired_pose_check slam_toolbox/srv/DesiredPoseChecker "{pose_x: 0.7, pose_y: 10.26, do_relocalization: true, search_distance: 8.
0}"                                                                                                                                                                                        
                                                                                                                                                                                                
requester: making request: slam_toolbox.srv.DesiredPoseChecker_Request(pose_x=0.7, pose_y=10.26, search_distance=8.0, do_relocalization=True)                                              
                                                                                                                                                                                           
response:                                                                                                                                                                                  
slam_toolbox.srv.DesiredPoseChecker_Response(best_response=0.6311222222222223, relocated_x=0.53, relocated_y=10.279999732971191, relocated_yaw=0.0, message='Found bestResponse', success=True)                                                                                                                                                                                       
                                                                                                                                                                                           
```

2024-10-02 06:54 UTC, merged